import {
  ffmpegBaseline,
  ffmpegReleaseDates,
  ffmpegReleaseDatesMeta,
} from ".";

/**
 * Smoke test for the ffmpeg release-dates snapshot. Verifies the map
 * loads, key format matches what compareFfmpegVersionToEpoch expects
 * (the version-as-printed-by-ffmpeg, no "n" prefix), and values are
 * ISO-8601 dates. The snapshot is regenerated by
 * `packages/platform/scripts/refresh-ffmpeg-release-dates.sh`.
 */

describe("ffmpegReleaseDates", () => {
  it("loads at least 100 release entries (snapshot is non-trivial)", () => {
    expect(Object.keys(ffmpegReleaseDates).length).toBeGreaterThan(100);
  });

  it("keys are version-string-as-printed (no leading n)", () => {
    for (const key of Object.keys(ffmpegReleaseDates)) {
      expect(key).not.toMatch(/^n/);
      // Two- or three-segment numeric versions; underscore allowed for
      // the rare "n4.4-mac" style we may not actually see.
      expect(key).toMatch(/^\d+\.\d+(?:\.\d+)?/);
    }
  });

  it("values are ISO-8601 dates (YYYY-MM-DD)", () => {
    for (const value of Object.values(ffmpegReleaseDates)) {
      expect(value).toMatch(/^\d{4}-\d{2}-\d{2}$/);
    }
  });

  it("exposes provenance metadata", () => {
    expect(ffmpegReleaseDatesMeta.generatedAt).toMatch(/^\d{4}-\d{2}-\d{2}$/);
    expect(ffmpegReleaseDatesMeta.source).toContain("FFmpeg");
    expect(ffmpegReleaseDatesMeta.releases).toBe(ffmpegReleaseDates);
  });

  it("contains the canonical recent releases users are likely on", () => {
    // Don't pin specific dates here — the snapshot moves — just assert
    // the lookup resolves to something for the well-known recent
    // tagged versions.
    for (const version of ["8.0.1", "8.0", "7.1.2", "7.1", "6.1"]) {
      expect(ffmpegReleaseDates[version]).toMatch(/^\d{4}-\d{2}-\d{2}$/);
    }
  });

  it("ffmpegBaseline stays available alongside the new export", () => {
    // Sanity: don't accidentally break the existing baseline import
    // path when adding releaseDates.
    expect(ffmpegBaseline).toBeDefined();
  });
});
