/**
 * Generate LAYOUT-ENVELOPE.md — per-invariant "where does my layout hold?".
 *
 * For every template that adopts the LAYOUT contract (its props schema exposes
 * `debugLayout`), sweep the aspect families × a scale range, resolve with
 * `debugLayout:true`, read the stamped `editor.layoutContract`, and report — per
 * declared invariant (`label · rule`) — the canvas range where it holds vs
 * breaks, with the boundary. Resolve + parse only, NO ffmpeg.
 *
 * This is the layout-solver report: instead of a green/red table it tells you
 * the feasible canvas envelope, so you either fix the geometry math for the
 * range you need or declare the template's supported output range as the proven
 * envelope. Run: `npm run audit:layout-envelope`.
 */
import * as fs from "node:fs";
import * as path from "node:path";

import type {
  MosaicDocument,
  MosaicEngineContext,
  MosaicTemplate,
  MosaicTemplateProps,
  MosaicLayoutContractStamp,
} from "@m0saic/types";
import { getTemplate, listRegisteredTemplateIds } from "@m0saic/template-utils";
import { proofCanvases, buildEnvelopeReport, type EnvelopeSample } from "./geometry-audit";

import "./m0saic"; // side-effect: register every template

const ROOT = path.resolve(__dirname, "..");
const OUT = path.join(ROOT, "LAYOUT-ENVELOPE.md");

// The sweep: aspect families across a scale range (override via env).
const AR = process.env.ENVELOPE_AR ?? "16:9,9:16,1:1";
const SCALES = process.env.ENVELOPE_SCALES ?? "240:2160";
const SCALE_STEP = Number(process.env.ENVELOPE_SCALE_STEP ?? 120);
const SWEEP_DESC = `ar ${AR} × scales ${SCALES} step ${SCALE_STEP}`;

function ctxFor(w: number, h: number): MosaicEngineContext {
  const t = { width: w, height: h, fps: 30, durationMs: 2000 };
  return { mode: "render", target: t, output: { ...t, workspaceDir: "/tmp/layout-env" }, media: {} } as unknown as MosaicEngineContext;
}

function adoptsLayout(tpl: MosaicTemplate<MosaicTemplateProps>): boolean {
  const schema = (tpl as { propsSchema?: Record<string, unknown> }).propsSchema;
  return !!schema && "debugLayout" in schema;
}

async function sampleAt(tpl: MosaicTemplate<MosaicTemplateProps>, w: number, h: number): Promise<EnvelopeSample | null> {
  try {
    const doc = (await tpl.render(
      { ...((tpl.defaultProps as MosaicTemplateProps) ?? {}), debugLayout: true } as MosaicTemplateProps,
      ctxFor(w, h),
    )) as MosaicDocument;
    const stamp: MosaicLayoutContractStamp | undefined = doc?.editor?.layoutContract;
    if (!stamp) return null;
    return { w, h, violated: stamp.violations.map((v) => `${v.label}|${v.rule}`) };
  } catch {
    // A resolve/flatten error is a total break: mark every declared invariant
    // as violated at this canvas via a sentinel key.
    return { w, h, violated: ["<render-error>"] };
  }
}

async function main(): Promise<void> {
  const ids = listRegisteredTemplateIds()
    .map(String)
    .filter((id) => {
      const t = getTemplate(id) as (MosaicTemplate<MosaicTemplateProps> & { deprecated?: unknown }) | undefined;
      return !!t && !t.deprecated && adoptsLayout(t);
    })
    .sort();

  const spec = { ar: AR, scales: SCALES, scaleStep: SCALE_STEP };
  const sections: string[] = [];
  for (const id of ids) {
    const tpl = getTemplate<MosaicTemplateProps>(id)!;
    const samples: EnvelopeSample[] = [];
    for (const [w, h] of proofCanvases(spec)) {
      process.stderr.write(`[layout-envelope] ${id} @ ${w}×${h} …\n`);
      const s = await sampleAt(tpl, w, h);
      if (s) samples.push(s);
    }
    if (samples.length === 0) continue;
    sections.push(buildEnvelopeReport(id, SWEEP_DESC, samples));
  }

  const header = ids.length === 0
    ? `# Layout envelope\n\n> Auto-generated by \`gen-layout-envelope\`. No template adopts the layout contract yet (expose a \`debugLayout\` prop + wrap the return in \`withLayoutContract\`).\n`
    : `# Layout envelope\n\n> Auto-generated by \`gen-layout-envelope\` — ${ids.length} adopting template(s), sweep ${SWEEP_DESC}.\n\n---\n\n`;
  fs.writeFileSync(OUT, header + sections.join("\n---\n\n"), "utf8");
  // eslint-disable-next-line no-console
  console.log(`[layout-envelope] wrote ${path.relative(ROOT, OUT)} — ${ids.length} adopting template(s)`);
}

main().catch((e) => {
  // eslint-disable-next-line no-console
  console.error(e);
  process.exit(1);
});
