/**
 * Generate GEOMETRY-MATRIX.md — the curated intent-vs-realized sweep.
 *
 * For every registered template that ADOPTS the geometry contract (its props
 * schema exposes `debugGeometry`), resolve `defaultProps + debugGeometry:true`
 * at each canvas in the principled tier set (composition-arithmetic §2:
 * modern-core / adjacent / hostile + the template's own outputHints), read the
 * stamped `editor.geometryContract` (resolve + parse only — NO ffmpeg), and
 * report ok / violations (kind · piece · axis · Δpx) / floors with a §3c routing
 * hint per failure.
 *
 * Deterministic: renders `defaultProps` (no wall-clock/random) with the debug
 * gate on. Run: `npm run audit:geometry-matrix`.
 */
import * as fs from "node:fs";
import * as path from "node:path";

import type {
  MosaicDocument,
  MosaicEngineContext,
  MosaicTemplate,
  MosaicTemplateProps,
  MosaicGeometryContractStamp,
} from "@m0saic/types";
import { getTemplate, listRegisteredTemplateIds } from "@m0saic/template-utils";
import { matrixCanvases, routingHint, isHostileCanvas } from "./geometry-audit";

import "./m0saic"; // side-effect: register every template

const ROOT = path.resolve(__dirname, "..");
const OUT = path.join(ROOT, "GEOMETRY-MATRIX.md");

function ctxFor(w: number, h: number): MosaicEngineContext {
  const t = { width: w, height: h, fps: 30, durationMs: 2000 };
  return { mode: "render", target: t, output: { ...t, workspaceDir: "/tmp/geom-matrix" }, media: {} } as unknown as MosaicEngineContext;
}

/** A template adopts the contract iff its props schema exposes `debugGeometry`. */
function adoptsContract(tpl: MosaicTemplate<MosaicTemplateProps>): boolean {
  const schema = (tpl as { propsSchema?: Record<string, unknown> }).propsSchema;
  return !!schema && "debugGeometry" in schema;
}

type CellResult = {
  w: number;
  h: number;
  tier: string;
  hostile: boolean;
  stamp?: MosaicGeometryContractStamp;
  error?: string;
};

async function stampAt(tpl: MosaicTemplate<MosaicTemplateProps>, w: number, h: number): Promise<Pick<CellResult, "stamp" | "error">> {
  try {
    const doc = (await tpl.render(
      { ...((tpl.defaultProps as MosaicTemplateProps) ?? {}), debugGeometry: true } as MosaicTemplateProps,
      ctxFor(w, h),
    )) as MosaicDocument;
    const stamp = doc?.editor?.geometryContract;
    if (!stamp) return { error: "no geometryContract stamp (debug gate not plumbed?)" };
    return { stamp };
  } catch (e) {
    return { error: String((e as Error)?.message ?? e).slice(0, 120) };
  }
}

function anchor(id: string): string {
  return id.toLowerCase().replace(/[^a-z0-9]+/g, "");
}

function violationLine(stamp: MosaicGeometryContractStamp): string {
  if (stamp.ok) return "✓";
  return stamp.violations
    .slice(0, 3)
    .map((v) => `${v.kind}${v.axis ? `/${v.axis}` : ""}${v.name ? ` \`${v.name}\`` : ""}${v.deltaPx != null ? ` Δ${v.deltaPx}px` : ""}`)
    .join("; ") + (stamp.violations.length > 3 ? ` …+${stamp.violations.length - 3}` : "");
}

function floorsCell(stamp: MosaicGeometryContractStamp): string {
  const f = stamp.floors;
  const spread = f.maxSpreadPx === Infinity ? "∞" : f.maxSpreadPx.toFixed(1);
  return `${f.feasible ? "feas" : "**INFEAS**"} · ${f.meetsPrecision ? "prec" : "sub-prec"} · spread ${spread}`;
}

async function main(): Promise<void> {
  const ids = listRegisteredTemplateIds()
    .map(String)
    .filter((id) => {
      const t = getTemplate(id) as (MosaicTemplate<MosaicTemplateProps> & { deprecated?: unknown }) | undefined;
      return !!t && !t.deprecated && adoptsContract(t);
    })
    .sort();

  const perTemplate: { id: string; cells: CellResult[]; failCount: number }[] = [];
  for (const id of ids) {
    const tpl = getTemplate<MosaicTemplateProps>(id)!;
    const outputHints = (tpl as { outputHints?: { width?: number; height?: number } }).outputHints;
    const cells: CellResult[] = [];
    for (const c of matrixCanvases(outputHints)) {
      process.stderr.write(`[geometry-matrix] ${id} @ ${c.w}×${c.h} …\n`);
      const { stamp, error } = await stampAt(tpl, c.w, c.h);
      cells.push({ w: c.w, h: c.h, tier: c.tier, hostile: isHostileCanvas(c.w, c.h), stamp, error });
    }
    const failCount = cells.filter((c) => c.error || (c.stamp && !c.stamp.ok)).length;
    perTemplate.push({ id, cells, failCount });
  }

  const out: string[] = [];
  out.push("# Template geometry matrix\n");
  out.push(
    "> Auto-generated by `gen-geometry-matrix` (do NOT edit by hand). For every " +
      "template that ADOPTS the geometry contract (props schema exposes " +
      "`debugGeometry`), resolves `defaultProps + debugGeometry:true` at the " +
      "principled canvas tiers (composition-arithmetic §2) and reads the stamped " +
      "`editor.geometryContract` — resolve + parse only, NO ffmpeg. A green row " +
      "means every computed rect survived to the pixels at that canvas. Hostile " +
      "canvases (primes / coprime pairs) degrade to EXACT placement — the " +
      "contract still holds. See the internal template-geometry-contract notes.\n",
  );

  const withFails = perTemplate.filter((t) => t.failCount > 0);
  out.push(`## ⚠ Violations (${withFails.length} template${withFails.length === 1 ? "" : "s"})\n`);
  if (withFails.length === 0) {
    out.push(`_None — all ${perTemplate.length} adopting template(s) hold at every canvas._\n`);
  } else {
    out.push("| template | failing canvases |");
    out.push("|---|---|");
    for (const t of withFails) out.push(`| [\`${t.id}\`](#${anchor(t.id)}) | ${t.failCount} |`);
    out.push("");
  }

  out.push(`**${perTemplate.length} adopting template(s) swept.**\n`);

  for (const t of perTemplate) {
    out.push(`### ${t.id}\n`);
    out.push(`- ${t.failCount === 0 ? "**all canvases hold** ✓" : `**${t.failCount} canvas(es) violate**`}\n`);
    out.push("| canvas | tier | result | floors |");
    out.push("|---|---|---|---|");
    for (const c of t.cells) {
      const result = c.error ? `⚠ ${c.error}` : violationLine(c.stamp!);
      const floors = c.error ? "—" : floorsCell(c.stamp!);
      out.push(`| ${c.w}×${c.h}${c.hostile ? " ¹" : ""} | ${c.tier} | ${result} | ${floors} |`);
    }
    out.push("");
    // Routing hints for the distinct failing kinds.
    const kinds = new Map<string, boolean>(); // kind → allHostile
    for (const c of t.cells) {
      if (!c.stamp || c.stamp.ok) continue;
      for (const v of c.stamp.violations) {
        const prev = kinds.get(v.kind);
        kinds.set(v.kind, prev === undefined ? c.hostile : prev && c.hostile);
      }
    }
    if (kinds.size > 0) {
      out.push("**Routing:**\n");
      for (const [kind, allHostile] of kinds) out.push(`- \`${kind}\` → ${routingHint(kind as never, allHostile)}`);
      out.push("");
    }
  }
  out.push("_¹ hostile canvas (prime / coprime axis) — degradation to exact placement is expected; the contract still asserts the exact intent._\n");

  fs.writeFileSync(OUT, out.join("\n") + "\n", "utf8");
  const totalFails = perTemplate.reduce((a, t) => a + t.failCount, 0);
  // eslint-disable-next-line no-console
  console.log(`[geometry-matrix] wrote ${path.relative(ROOT, OUT)} — ${perTemplate.length} template(s), ${totalFails} failing cell(s)`);
}

main().catch((e) => {
  // eslint-disable-next-line no-console
  console.error(e);
  process.exit(1);
});
