// Which template ids Mosaic Web can open — read from `web-template-ids.json`.
//
// The file is generated by the package build (`gen-web-template-ids.ts`) from
// the BROWSER entry's registrations, so it is the web registry by construction:
// a `/make?t=<id>` link resolves in Mosaic Web exactly when `isWebTemplateId(id)`.
// Node-only module (reads the file) — exported from the node `index` entry, never
// from `./web`.
import * as fs from "node:fs";
import * as path from "node:path";

/** Package-root file the build writes; ships in the tarball alongside `template-manifest.json`. */
export const WEB_TEMPLATE_IDS_FILE = "web-template-ids.json";

let cachedIds: ReadonlySet<string> | null = null;

/**
 * Load the set once. A missing or malformed file yields the EMPTY set: nothing
 * is "on web", so a consumer prints no web link — the safe failure, never a
 * crash on a render path.
 */
function webTemplateIds(): ReadonlySet<string> {
  if (cachedIds) return cachedIds;
  let ids: string[] = [];
  try {
    const file = path.resolve(__dirname, "..", WEB_TEMPLATE_IDS_FILE);
    const parsed = JSON.parse(fs.readFileSync(file, "utf8")) as { ids?: unknown };
    if (Array.isArray(parsed.ids)) {
      ids = parsed.ids.filter((id): id is string => typeof id === "string");
    }
  } catch {
    // Not built yet / pruned from an install — treated as "no template is on web".
  }
  cachedIds = new Set(ids);
  return cachedIds;
}

/** Every template id the web build registers, sorted. */
export function listWebTemplateIds(): string[] {
  return Array.from(webTemplateIds()).sort();
}

/** Can Mosaic Web open this template id (exact-match membership, like the web receiver)? */
export function isWebTemplateId(id: string): boolean {
  return webTemplateIds().has(String(id));
}
