/**
 * ============================================================================
 * @m0saic/charts/line-chart — Animation timing (pure)
 * ============================================================================
 *
 * Timing math + FFmpeg-safe easing for the line-chart intro. PURE +
 * deterministic — no side effects, no registration, no wall clock (every value
 * derives from the resolved `AnimConfig`, itself derived from `ctx.target`).
 *
 * v1 intro = a left→right DRAW-ON. `line-series.ts` paints the finished
 * line/area/markers as STATIC mask atlases and reveals them with ONE curtain
 * (`buildCurtainColumns` here → `curtainSource`): hide-colored plot columns that
 * pop open (a free `enable=` gate) on the same ease the cascade used. Value
 * labels reuse `pointStartSec` as an `overlay.enable` gate. `sliverTiming` /
 * `sweepInverseEase` are the LEGACY per-sliver schedule — retained (exported)
 * only for back-compat + the geometry tests; the live path no longer uses them.
 *
 * TIME UNITS: seconds (matches FFmpeg `t` / overlay.startAtSec).
 * ============================================================================
 */

import type { AnimConfig, EaseName } from "./types";

export type SeriesTiming = { startAtSec: number; endAtSec: number };

/** Absolute start/end timestamps for a series' intro. */
export function computeSeriesTiming(index: number, anim: AnimConfig): SeriesTiming {
  const startAtSec = anim.intro.delaySec + index * anim.intro.staggerSec;
  const endAtSec = startAtSec + anim.intro.durationSec;
  return { startAtSec, endAtSec };
}

/** Map a normalized progress var u∈[0..1] → eased∈[0..1] (FFmpeg-safe). */
export function easingExpr(ease: EaseName, uVar = "u"): string {
  if (ease === "smoothstep" || ease === "easeInOut") {
    return `(${uVar})*(${uVar})*(3-2*(${uVar}))`;
  }
  return `${uVar}`; // linear
}

// NOTE: alpha expressions are generated by the canonical `fadeInExpr` from
// @m0saic/template-utils (min/max + global `t` — the form ffmpeg AND the web
// preview evaluator both accept). Do NOT hand-roll `clip`/`lt`: `clip` is
// unsupported by the preview evaluator and silently evaluates to 0 (⇒ invisible
// layer). Animated alpha works on lavfi/masked-tile + mosaic-ref layers, NOT on
// media-image overlays.

// ---------------------------------------------------------------------------
// Draw-on sweep schedule (LEGACY per-sliver cascade — superseded by the curtain
// reveal below; kept + exported for back-compat and the geometry tests).
// ---------------------------------------------------------------------------

/**
 * Inverse of the reveal easing: at what normalized time u does the sweep reach
 * arc-length fraction p? Front-loads `easeOut`; identity for the rest (the
 * per-sliver `fadeInExpr` already supplies visual easing).
 */
export function sweepInverseEase(ease: EaseName, p: number): number {
  const c = Math.max(0, Math.min(1, p));
  if (ease === "easeInOut") return 1 - Math.sqrt(1 - c); // gentle front-load
  return c; // linear / smoothstep ⇒ even pace
}

export type SliverTiming = { startSec: number; fadeDur: number };

/**
 * Schedule one sliver: when it starts revealing and how long it fades. With
 * `fadeDur` ≈ 2.5 sliver-intervals the fades overlap into a continuous draw.
 */
export function sliverTiming(frac0: number, sliverCount: number, anim: AnimConfig): SliverTiming {
  const intro = anim.intro;
  const startSec = intro.delaySec + intro.durationSec * sweepInverseEase(intro.ease, frac0);
  const fadeDur = Math.max(0.05, (intro.durationSec / Math.max(1, sliverCount)) * 2.5);
  return { startSec, fadeDur };
}

/** When a point marker reveals (just after the sweep passes its vertex). */
export function pointStartSec(vertexFrac: number, anim: AnimConfig): number {
  const intro = anim.intro;
  return intro.delaySec + intro.durationSec * sweepInverseEase(intro.ease, vertexFrac);
}

/** Chrome (grid/axes/labels) establishing-fade window: quick, before the draw. */
export function chromeFade(anim: AnimConfig): { startSec: number; durSec: number } {
  return { startSec: 0, durSec: Math.min(0.35, anim.intro.durationSec * 0.35) };
}

// ---------------------------------------------------------------------------
// Curtain reveal (R6) — the draw-on as ONE lavfi track instead of N overlays.
//
// The finished line/area/markers are painted ONCE (static mask atlases); a
// column of hide-colored boxes covers the plot and each box disables (pops)
// when the sweep reaches its x. `columnRevealSec` keys each column to the SAME
// ease as the old per-sliver cascade, so the pacing matches the fade version.
// ---------------------------------------------------------------------------

/** One curtain column: an absolute-px box hidden until `revealAtSec`. */
export type CurtainColumn = { x: number; y: number; w: number; h: number; revealAtSec: number };

/** When the curtain uncovers x-fraction `xFrac∈[0..1]` of the plot — the same
 *  ease/pacing as a point-marker reveal at that fraction. */
export function columnRevealSec(xFrac: number, anim: AnimConfig): number {
  return pointStartSec(xFrac, anim);
}

/**
 * Tile the plot rect with `K = clamp(round(plotW/stepPx), 24, 120)` full-height
 * columns walking left→right, each revealing at `columnRevealSec(centerXFrac)`.
 * `padPx` bleeds the coverage outward so markers/strokes that overhang the plot
 * edges (top marker at the max value, first/last marker on the plot border) stay
 * hidden until their column opens. Pure + deterministic.
 */
export function buildCurtainColumns(
  plot: { left: number; right: number; top: number; bottom: number },
  anim: AnimConfig,
  opts: { stepPx?: number; padPx?: number } = {},
): CurtainColumn[] {
  const stepPx = opts.stepPx ?? 16;
  const padPx = Math.max(0, opts.padPx ?? 0);
  const plotW = Math.max(1, plot.right - plot.left);
  const x0 = plot.left - padPx;
  const x1 = plot.right + padPx;
  const yTop = Math.round(plot.top - padPx);
  const h = Math.max(1, Math.round(plot.bottom + padPx) - yTop);
  const span = x1 - x0;
  const K = Math.max(24, Math.min(120, Math.round(plotW / stepPx)));
  const cols: CurtainColumn[] = [];
  for (let k = 0; k < K; k++) {
    const l = x0 + (span * k) / K;
    const r = x0 + (span * (k + 1)) / K;
    const lx = Math.round(l);
    const w = Math.round(r) - lx;
    if (w <= 0) continue;
    const xFrac = Math.max(0, Math.min(1, ((l + r) / 2 - plot.left) / plotW));
    cols.push({ x: lx, y: yTop, w, h, revealAtSec: columnRevealSec(xFrac, anim) });
  }
  return cols;
}
