/**
 * Browser-compatible dictionary export.
 *
 * ## Import strategy
 *
 * Consumers should always import from `@m0saic/dictionary`:
 *
 *   import { entries, generators, resolveM0saic } from "@m0saic/dictionary";
 *
 * - **Browser bundles** (webpack, vite, etc.): the bundler resolves to this
 *   file via the `"browser"` field in package.json. DSL strings are inlined
 *   — light entries as literals, brand entries from their generated
 *   `m0.json` (tools/validate.js, ≤ 40 KB). Only the m-33 bitmap ships
 *   `m0: ""` and must be resolved via `resolveM0saic(entry)`, which fetches
 *   from the server.
 *
 * - **Node / CLI**: resolves to `index.ts` which reads .m0 files from disk.
 *
 * Both exports use the same `MosaicDictionaryEntryResolved` type. The only
 * difference is how the m0saic payload is loaded (inlined vs fs.readFileSync).
 *
 * Do NOT import this file directly — use `@m0saic/dictionary`.
 * The bundler handles resolution automatically.
 *
 * ## How each entry is constructed
 *
 * The dictionary's source of truth for metadata (title, description, tags,
 * `complexity`, `feasibility`, `sourceResolution`, etc.) is each entry's
 * `metadata.json` file. The build script (`tools/validate.js`) writes the
 * precomputed `complexity`/`feasibility`/`sourceResolution` fields back into
 * those files on every build, so they're always in sync with the .m0.
 *
 * This file imports each entry's metadata.json and only overrides:
 *   - `m0`: inline DSL string for light entries, "" for heavy entries
 *   - `m0File`: path to the .m0 file (heavy entries only, for lazy resolve)
 *   - `preview.src`: rewritten to be relative to the dictionary dist root
 *     (the path in metadata.json is relative to the entry directory)
 *
 * Adding a new entry: create the metadata.json + m0saic.m0 in
 * `src/entries/<category>/<slug>/`, run `npm run dictionary:validate` (which
 * populates the precomputed fields), then add an import + entry stub here.
 */
import type { MosaicDictionaryEntryResolved } from "@m0saic/types";

// ── splits ────────────────────────────────────────────────
import splits2colMeta from "./entries/splits/2-col/metadata.json";
import splits2rowMeta from "./entries/splits/2-row/metadata.json";
import splits3colMeta from "./entries/splits/3-col/metadata.json";
import splits3rowMeta from "./entries/splits/3-row/metadata.json";
import splits4colMeta from "./entries/splits/4-col/metadata.json";
import splits4rowMeta from "./entries/splits/4-row/metadata.json";
import splits21colMeta from "./entries/splits/2-1-col/metadata.json";
import splits12colMeta from "./entries/splits/1-2-col/metadata.json";
import splits21rowMeta from "./entries/splits/2-1-row/metadata.json";
import splits12rowMeta from "./entries/splits/1-2-row/metadata.json";

// ── grids ─────────────────────────────────────────────────
import grids2x2Meta from "./entries/grids/2x2/metadata.json";
import grids2x3Meta from "./entries/grids/2x3/metadata.json";
import grids3x2Meta from "./entries/grids/3x2/metadata.json";
import grids3x3Meta from "./entries/grids/3x3/metadata.json";
import grids4x4Meta from "./entries/grids/4x4/metadata.json";

// ── layouts ───────────────────────────────────────────────
import layoutsHeroSidebarMeta from "./entries/layouts/hero-sidebar/metadata.json";
import layoutsHeroBottomStripMeta from "./entries/layouts/hero-bottom-strip/metadata.json";
import layoutsHeroTopStripMeta from "./entries/layouts/hero-top-strip/metadata.json";
import layoutsSidebarMainMeta from "./entries/layouts/sidebar-main/metadata.json";
import layoutsLShapeMeta from "./entries/layouts/l-shape/metadata.json";
import layoutsTShapeMeta from "./entries/layouts/t-shape/metadata.json";
import layoutsThreeUpMeta from "./entries/layouts/three-up/metadata.json";
import layoutsMainTwoSupportingMeta from "./entries/layouts/main-two-supporting/metadata.json";
import layoutsStackedPairsMeta from "./entries/layouts/stacked-pairs/metadata.json";
import layoutsFeatureSidebarMeta from "./entries/layouts/feature-sidebar/metadata.json";
import layoutsColumnGridMeta from "./entries/layouts/column-grid/metadata.json";
import layoutsWideFeatureMeta from "./entries/layouts/wide-feature/metadata.json";
import layoutsBottomFeatureMeta from "./entries/layouts/bottom-feature/metadata.json";
import layoutsDenseDashboardMeta from "./entries/layouts/dense-dashboard/metadata.json";

// ── brand ─────────────────────────────────────────────────
import brandM33Meta from "./entries/brand/m-33/metadata.json";
import brandM33BitmapMeta from "./entries/brand/m-33_bitmap/metadata.json";
import brandM0saicPatternMeta from "./entries/brand/m0saic-pattern/metadata.json";
import brandM0Meta from "./entries/brand/m0/metadata.json";
import brandQrMeta from "./entries/brand/qr/metadata.json";
// The brand m0s the browser ships INLINE — generated by tools/validate.js
// (`m0.json`, canonical, ≤ INLINE_M0_MAX_CHARS) so templates that read
// `entry.m0` synchronously work on web: QR Code's centre M, Brand Marks,
// community-m. The 149 KB bitmap stays lazy (`m0File`).
import brandM33M0 from "./entries/brand/m-33/m0.json";
import brandM0saicPatternM0 from "./entries/brand/m0saic-pattern/m0.json";
import brandM0M0 from "./entries/brand/m0/m0.json";
import brandQrM0 from "./entries/brand/qr/m0.json";

/**
 * Compose an entry by spreading its metadata.json over a small set of
 * browser-specific overrides. The cast at the end is necessary because
 * TypeScript can't statically prove that imported JSON satisfies the
 * `MosaicDictionaryEntryResolved` discriminated union (the `category`
 * field comes through as a literal string, not the typed union).
 */
function entry(
  meta: object,
  overrides: { m0: string; m0File?: string; preview?: { mode: "image"; src: string } },
): MosaicDictionaryEntryResolved {
  return { ...meta, ...overrides } as unknown as MosaicDictionaryEntryResolved;
}

const ENTRIES: MosaicDictionaryEntryResolved[] = [
  // ── splits ────────────────────────────────────────────────
  entry(splits2colMeta,  { m0: "2(F,F)" }),
  entry(splits2rowMeta,  { m0: "2[F,F]" }),
  entry(splits3colMeta,  { m0: "3(F,F,F)" }),
  entry(splits3rowMeta,  { m0: "3[F,F,F]" }),
  entry(splits4colMeta,  { m0: "4(F,F,F,F)" }),
  entry(splits4rowMeta,  { m0: "4[F,F,F,F]" }),
  entry(splits21colMeta, { m0: "3(0,F,F)" }),
  entry(splits12colMeta, { m0: "3(F,0,F)" }),
  entry(splits21rowMeta, { m0: "3[0,F,F]" }),
  entry(splits12rowMeta, { m0: "3[F,0,F]" }),

  // ── grids ─────────────────────────────────────────────────
  entry(grids2x2Meta, { m0: "2[2(F,F),2(F,F)]" }),
  entry(grids2x3Meta, { m0: "3[2(F,F),2(F,F),2(F,F)]" }),
  entry(grids3x2Meta, { m0: "2[3(F,F,F),3(F,F,F)]" }),
  entry(grids3x3Meta, { m0: "3[3(F,F,F),3(F,F,F),3(F,F,F)]" }),
  entry(grids4x4Meta, { m0: "4[4(F,F,F,F),4(F,F,F,F),4(F,F,F,F),4(F,F,F,F)]" }),

  // ── layouts ───────────────────────────────────────────────
  entry(layoutsHeroSidebarMeta,        { m0: "2(F,2[F,F])" }),
  entry(layoutsHeroBottomStripMeta,    { m0: "2[F,3(F,F,F)]" }),
  entry(layoutsHeroTopStripMeta,       { m0: "2[3(F,F,F),F]" }),
  entry(layoutsSidebarMainMeta,        { m0: "2(2[F,F],F)" }),
  entry(layoutsLShapeMeta,             { m0: "2[2(F,F),2(F,-)]" }),
  entry(layoutsTShapeMeta,             { m0: "2[3(F,F,F),3(-,F,-)]" }),
  entry(layoutsThreeUpMeta,            { m0: "2[F,2(F,F)]" }),
  entry(layoutsMainTwoSupportingMeta,  { m0: "3[0,F,2(F,F)]" }),
  entry(layoutsStackedPairsMeta,       { m0: "3[2(F,F),2(F,F),3(F,F,F)]" }),
  entry(layoutsFeatureSidebarMeta,     { m0: "2[3(F,F,F),2(F,2[F,F])]" }),
  entry(layoutsColumnGridMeta,         { m0: "2(2[F,F],2[2(F,F),2(F,F)])" }),
  entry(layoutsWideFeatureMeta,        { m0: "2[4(>,F,F,F),4(F,F,F,F)]" }),
  entry(layoutsBottomFeatureMeta,      { m0: "2[3(F,F,F),4(>,F,F,F)]" }),
  entry(layoutsDenseDashboardMeta,     { m0: "3[4(F,F,F,F),4(F,F,F,F),4(>,F,F,F)]" }),

  // ── brand (image preview; m0 inline from the generated m0.json, masks
  //    and rank sets ride in metadata.json — the whole entry is on web) ─
  // NOTE: m0saic-m-64, m0saic-m-256, m0saic-m-rects moved to @m0saic/dictionary-private
  entry(brandM33Meta, {
    m0: brandM33M0.m0,
    m0File: "entries/brand/m-33/m0saic.m0c",
    preview: { mode: "image", src: "entries/brand/m-33/preview.png" },
  }),
  // The one heavy entry (272² bitmap, 36 770 frames): lazy via resolveM0saic.
  entry(brandM33BitmapMeta, {
    m0: "",
    m0File: "entries/brand/m-33_bitmap/m0saic.m0",
  }),
  entry(brandM0saicPatternMeta, {
    m0: brandM0saicPatternM0.m0,
    m0File: "entries/brand/m0saic-pattern/m0saic.m0c",
    preview: { mode: "image", src: "entries/brand/m0saic-pattern/preview.png" },
  }),
  entry(brandM0Meta, {
    m0: brandM0M0.m0,
    m0File: "entries/brand/m0/m0saic.m0c",
    preview: { mode: "image", src: "entries/brand/m0/preview.png" },
  }),
  entry(brandQrMeta, {
    m0: brandQrM0.m0,
    m0File: "entries/brand/qr/m0saic.m0c",
  }),
];

export const entries = {
  all: ENTRIES,
  byId: Object.fromEntries(ENTRIES.map((e) => [e.id, e])) as Record<
    string,
    MosaicDictionaryEntryResolved
  >,
};

// Re-export generators — they use @m0saic/dsl-stdlib which is browser-safe.
import * as _generators from "./generators";
export const generators = _generators;

// Re-export operations — pure descriptor data, browser-safe.
import * as _operations from "./operations";
export const operations = _operations;
export type { OperationDescriptor, OperationKind } from "./operations";

// Re-export lazy resolver for heavy entries.
export {
  resolveM0saic,
  setDictionaryAssetsBase,
  dictionaryAssetsBase,
} from "./resolve";

// Re-export source-order StableKey helper. Pure DSL parsing — browser-safe.
export {
  getSourceOrderStableKeys,
  getSourceOrderStableKeysForM0,
} from "./sourceOrder";

// Registry for extensible multi-dictionary support.
import { registry } from "./registry";
export { registry, DictionaryRegistry } from "./registry";

// Auto-register the official dictionary (browser entry point)
const byId = Object.fromEntries(ENTRIES.map((e) => [e.id, e])) as Record<string, MosaicDictionaryEntryResolved>;
registry.register({
  name: "@m0saic/dictionary",
  all: ENTRIES,
  byId,
  // Rank sets ride in metadata.json, so they are on web — same lookup as the
  // node entry (`entries/__generated__.ts`). Until 2026-09-16 this threw
  // "not available in browser bundle", which took Brand Marks down on web.
  getRankSet(entryId, name) {
    const entry = byId[entryId];
    if (!entry) throw new Error(`Dictionary entry not found: "${entryId}"`);
    const rs = entry.rankSets?.[name];
    if (!rs) throw new Error(`Rank set not found: entry="${entryId}" name="${name}"`);
    return rs;
  },
  // Named mask SETS are resolved from mask files at node load time
  // (`maskSetsResolved`); nothing populates them here, so the same
  // "not found" the node entry gives for a missing set. Per-frame `masks`
  // (what every shipped template uses) are on the entry itself.
  getMaskSet(entryId, name) {
    const entry = byId[entryId];
    if (!entry) throw new Error(`Dictionary entry not found: "${entryId}"`);
    const ms = entry.maskSetsResolved?.[name];
    if (!ms) throw new Error(`Mask set not found: entry="${entryId}" name="${name}" (named mask sets are not bundled for the browser)`);
    return ms;
  },
  assetsBasePath: "/dictionary",
});

// ── Scoring ──
// Moved to @m0saic/momo/scoring. Import from there directly — the dictionary
// no longer re-exports it (breaks the dictionary↔momo build cycle).
